/** Declaration file generated by dts-gen */

declare module "@iconify/json-tools" {

    import { ExtendedIconifyIcon, IconifyIcon, IconifyIcons, IconifyJSON } from "@iconify/types";

    interface ScriptifyOptions {
        icons?: string[],
        optimize?: boolean,
        pretty?: boolean,
        callback?: string
    }

    export class Collection {
        constructor(prefix?: string);

        addAlias(name: string, parent: string, data?: object): boolean;

        addIcon(name: string, data: ExtendedIconifyIcon): boolean;

        getIconData(name: string, normalized?: boolean): IconifyIcon | null;

        getIcons(icons?: string[] | null, notFound?: boolean): IconifyIcons | null;

        iconExists(name: string): boolean;

        listIcons(includeAliases?: boolean): string[];

        loadFromFile(file: string, defaultPrefix?: string): boolean;

        loadFromFileAsync(file: string, defaultPrefix?: string): Promise<Collection>;

        loadIconifyCollection(name: string, dir?: string): boolean;

        loadJSON(data: string | IconifyJSON, defaultPrefix?: string): boolean;

        prefix(): boolean | string;

        removeIcon(icon: string, checkAliases?: boolean): void;

        scriptify(options?: ScriptifyOptions): string;

        setDefaultIconValue(key: string, value: number | boolean): void;

        static addMissingAttributes(data: IconifyIcon): IconifyIcon;

        static deOptimize(data: IconifyJSON): void;

        static findIconifyCollection(name: string, dir?: string): string;

        static optimize(json: IconifyJSON, props: string[]): void;

    }

    export class SVG {
        constructor(icon: IconifyIcon);

        getAttributes(props: object): string;

        getSVG(props: object, addExtra?: boolean): string;

        static calculateDimension(size: string | number, ratio: number, precision?: number): string | number | null;

        static replaceIDs(body: string): string;

        static splitAttributes(props: object): { icon: object, node: object };

    }

    export function Normalize(data: IconifyIcon): IconifyIcon;

}
